name: Lint
on: workflow_call
permissions: {}
jobs:
  flake:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-nix
    - uses: DeterminateSystems/flake-checker-action@de924abd783455e8429c858962b9e43062d19da1 # v13
      with:
        send-statistics: false
        ignore-missing-flake-lock: false
        fail-mode: true
  checks:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-nix
    - name: Flake checks
      run: nix flake check --all-systems
  editorconfig:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-nix
    - name: Lint editorconfig
      run: nix develop .#lintEditorconfig -c editorconfig-checker -f github-actions
  workflows:
    runs-on: ubuntu-24.04-arm
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-nix
    - name: Lint workflows
      run: nix develop .#lintWorkflows -c zizmor --format sarif . > workflow_results.sarif
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload workflow report
      uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4.37.1
      with:
        sarif_file: workflow_results.sarif
        category: zizmor
